owner: qwq-ooo
repo: upptime

sites:
  - name: 浅滩 qwq.ooo - Mastodon Server
    slug: qwq-ooo
    url: https://qwq.ooo/api/v2/instance
    maxResponseTime: 20000
  - name: Islet - Mastodon Media Storage
    slug: islet
    url: https://islet.qwq.ooo
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 404
  - name: Matrix Server
    slug: matrix
    url: https://matrix.qwq.ooo/_matrix/federation/v1/version
    maxResponseTime: 20000
  - name: Gitea
    slug: gitea
    url: https://git.foxb612.com/api/v1/version
    maxResponseTime: 20000

status-website:
  cname: status.qwq.ooo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: QWQ.OOO Status
  introTitle: "QWQ.OOO Status"
  introMessage: ""
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"
