owner: qwq-ooo
repo: upptime

sites:
  - name: 浅滩 qwq.ooo - Mastodon Server
    slug: qwq-ooo
    url: https://qwq.ooo
    maxResponseTime: 20000
  - name: Islet - Media Storage
    slug: islet
    url: https://islet.qwq.ooo
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 404

status-website:
  cname: status.qwq.ooo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: QWQ.OOO Status
  introTitle: "QWQ.OOO Status"
  introMessage: ""
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
